# Rough position of table
# That is where the 3D sensor will look for the table and objects on top of it 
geometry_msgs/PointStamped table_position

---

# Pose of the recognised object
geometry_msgs/PoseStamped object_pose
# Name of the recognised object
string object_name
# Type of the recognised object
string object_type
# Human-readable error description
string error_message
# Code of the error above
int8 error_code

---

# Current state of object recognition 
string process_state