# Rough position of table
# That is where the 3D sensor will look for the table and objects on top of it 
# Optional; won't move head, if empty
geometry_msgs/PointStamped table_position

---

# Poses of the recognised objects
geometry_msgs/PoseStamped[] object_poses
# Names of the recognised objects
string[] object_names
# Types of the recognised objects
string[] object_types
# Human-readable error description
string error_message
# Code of the error above
int8 error_code

---

# Current state of object recognition 
string process_state
